### ISSUE TITLE
v8::FunctionTemplate inherit to Napi

### ISSUE THREAD

**Issue by iclosure** [nodejs/node-addon-api#246] opened 2018-04-23 11:43 UTC
Can we implement v8::FunctionTemplate::Inherit in Napi ?

**Comment by gabrielschulhof** [comment] 2018-04-23 12:47
`FunctionTemplate` is a V8-specific concept, whereas we're trying to keep N-API VM-agnostic. The behaviour of `Inherit` can be achieved with existing APIs.

**Comment by NickNaso** [comment] 2018-04-23 12:56
Hi everyone,
@gabrielschulhof you're right, but I think that this is a duplicate issue, there is a discussion about ```Inherit``` **[here https://github.com/nodejs/node-addon-api/issues/229](https://github.com/nodejs/node-addon-api/issues/229)**

**Comment by iclosure** [comment] 2018-04-23 14:07
Can you show me the exmaple @gabrielschulhof . Thank you

**Comment by iclosure** [comment] 2018-04-23 16:05
But the method in 'super class' is invalid. How can I fix it?

**Comment by gabrielschulhof** [comment] 2018-04-23 16:18
@iclosure can you show me the code?

**Comment by iclosure** [comment] 2018-04-23 16:30
1) Super Init:
void BaseObject::Initialize(Napi::Env env, Napi::Object exports)
{
    Napi::HandleScope scope(env);
    std::vector<PropertyDescriptor> properties = {
        InstanceAccessor("objectType", &BaseObject::GetObjectType, nullptr),
        InstanceAccessor("id", &BaseObject::GetId, &BaseObject::SetId),
        InstanceAccessor("domain", &BaseObject::GetDomain, &BaseObject::SetDomain),
        InstanceAccessor("name", &BaseObject::GetName, &BaseObject::SetName),
        InstanceAccessor("mark", &BaseObject::GetMark, &BaseObject::SetMark),
        InstanceAccessor("desc", &BaseObject::GetDesc, &BaseObject::SetDesc),
        InstanceMethod("isPrivateMark", &BaseObject::IsPrivateMark),
        InstanceMethod("childCount", &BaseObject::ChildCount),
        InstanceMethod("objectTypeString", &BaseObject::ObjectTypeString),
        InstanceMethod("resetData", &BaseObject::ResetData),
        InstanceMethod("clearData", &BaseObject::ClearData),
        InstanceMethod("domainOfType", &BaseObject::DomainOfType)
    };
    ctor = napi_init<BaseObject>(env, exports, "Object", properties);
}

2) Sub Class inherit:

template<typename Sub, typename Super>
inline Napi::FunctionReference napi_init(Napi::Env env, Napi::Object exports, const char *name,
                                         const std::vector<Napi::ClassPropertyDescriptor<Sub> > &properties)
{
    Napi::HandleScope scope(env);
    Napi::Function object = Sub::DefineClass(env, name, properties);
    napi_inherits(env, object, Super::ctor.Value());
    exports.Set(name, object);
    Napi::FunctionReference ctor = Napi::Persistent(object);
    ctor.SuppressDestruct();
    return ctor;
}
3) Javascript code:
var vehicle = new proto.Vehicle();
console.log(vehicle.clearData);
vehicle.clearData(null);

**Comment by iclosure** [comment] 2018-04-23 16:44
<img width="1280" alt="screen shot 2018-04-24 at 00 44 20" src="https://user-images.githubusercontent.com/11292223/39140921-a87faab2-4758-11e8-91cc-a53a26392271.png">

**Comment by gabrielschulhof** [comment] 2018-04-23 20:33
@iclosure I created an [example](https://github.com/nodejs/abi-stable-node-addon-examples/pull/20) using plain C N-API.

**Comment by iclosure** [comment] 2018-04-24 11:38
It is helpful for static method to inherit and object's member properties!  But the member method of super object cannot be inherited by sub-class. The examples as bellow:
    The super-class method:
    `InstanceMethod("clearData", &BaseObject::ClearData)`
    I want to call the method "clearData" of super-class on sub-class in javascript, like this:
    `var obj = new addon.MySubObject();
      obj.clearData`
  My error tip is, "TypeError: Illegal invocation".
  How can I resolve this issue, please show me an example, thank you!!!😊

**Comment by gabrielschulhof** [comment] 2018-04-24 14:12
@iclosure I have reproduced the problem. I'll try and find the reason.

**Comment by gabrielschulhof** [comment] 2018-04-24 14:30
```JS
// ES6 notation

class SuperClass {
  constructor() {
    console.log("SuperClass constructor");
  }
  superclassMethod() {
    console.log("SuperClass method");
  }
}

class SubClass extends SuperClass {
  constructor() {
    super();
    console.log("SubClass constructor");
  }
}

const x = new SubClass();
x.superclassMethod();

// Old style

const OldSuperClass = function OldSuperClass() {
  console.log("OldSuperClass constructor");
};

OldSuperClass.prototype.oldsuperclassMethod = function oldsuperclassMethod() {
  console.log("OldSuperClass method");
};

const OldSubClass = function OldSubClass() {
  OldSuperClass.apply(this, arguments);
  console.log("OldSubClass constructor");
};

Object.setPrototypeOf(OldSubClass.prototype, OldSuperClass.prototype);
Object.setPrototypeOf(OldSubClass, OldSuperClass);

const y = new OldSubClass();
y.oldsuperclassMethod();

// Native

const addon = require('./build/Release/inheritance.node');

const z = new addon.Subclass();
z.superclassMethod(); // <-- Throws illegal invocation error
```

**Comment by gabrielschulhof** [comment] 2018-05-07 18:20
A link to that commit: https://github.com/nodejs/node/commit/08a5b442e4

**Comment by iclosure** [comment] 2019-07-21 02:39
@gabrielschulhof Has any solution for this? :)

**Comment by iclosure** [comment] 2019-07-21 02:39
Has any solution for this now? :)

**Comment by iclosure** [comment] 2019-07-21 02:41
@gabrielschulhof Has any solution for this? :)

**Comment by gabrielschulhof** [comment] 2019-07-21 03:13
@iclosure there is no easy solution, because, in order to do it properly, we'd need to be able to retrieve the `v8::FunctionTemplate` from V8 after the fact. Now, some constructors, such as those for built-in objects may not even have a `v8::FunctionTemplate`.

Either way, implementing this without the support of the V8 folks would result in pretty limited support.

**Comment by gabrielschulhof** [comment] 2019-07-21 03:21
@iclosure with V8 as it is now, we could only support inheritance if both the parent class and the child class were created using N-API.

**Comment by iclosure** [comment] 2019-07-22 04:43
Get it,Thanks!😊

**Comment by mhdawson** [comment] 2019-07-22 21:55
@iclosure ok if we close this issue now?

**Closed** 2019-07-29 13:13 UTC
