### ISSUE TITLE
Failed in "npm run  test"

### ISSUE THREAD

**Issue by gzx-miller** [nodejs/node-addon-api#765] opened 2020-07-14 08:30 UTC
14 verbose lifecycle node-addon-api@3.0.1~test: CWD: D:\DCode\electron\node-addon-api
15 silly lifecycle node-addon-api@3.0.1~test: Args: [ '/d /s /c', 'node test' ]
16 silly lifecycle node-addon-api@3.0.1~test: Returned: code: 9  signal: null
17 info lifecycle node-addon-api@3.0.1~test: Failed to exec test script
18 verbose stack Error: node-addon-api@3.0.1 test: `node test`
18 verbose stack Exit status 9
18 verbose stack     at EventEmitter.<anonymous> (C:\Users\guozhenxing\AppData\Roaming\nvm\v8.17.0\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
18 verbose stack     at emitTwo (events.js:126:13)
18 verbose stack     at EventEmitter.emit (events.js:214:7)
18 verbose stack     at ChildProcess.<anonymous> (C:\Users\guozhenxing\AppData\Roaming\nvm\v8.17.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
18 verbose stack     at emitTwo (events.js:126:13)
18 verbose stack     at ChildProcess.emit (events.js:214:7)
18 verbose stack     at maybeClose (internal/child_process.js:915:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
19 verbose pkgid node-addon-api@3.0.1
20 verbose cwd D:\DCode\electron\node-addon-api
21 verbose Windows_NT 10.0.18362
22 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
23 verbose node v8.17.0
24 verbose npm  v6.13.4
25 error code ELIFECYCLE
26 error errno 9
27 error node-addon-api@3.0.1 test: `node test`
27 error Exit status 9
28 error Failed at the node-addon-api@3.0.1 test script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 9, true ]

**Comment by gzx-miller** [comment] 2020-07-14 08:35
I use node 10.14.1, find same issue.
18 verbose stack Error: node-addon-api@3.0.1 test: `node test`
18 verbose stack Exit status 3221226356
18 verbose stack     at EventEmitter.<anonymous> (C:\Users\guozhenxing\AppData\Roaming\nvm\v10.14.2\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
18 verbose stack     at EventEmitter.emit (events.js:182:13)
18 verbose stack     at ChildProcess.<anonymous> (C:\Users\guozhenxing\AppData\Roaming\nvm\v10.14.2\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:182:13)
18 verbose stack     at maybeClose (internal/child_process.js:962:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
19 verbose pkgid node-addon-api@3.0.1
20 verbose cwd D:\DCode\electron\node-addon-api
21 verbose Windows_NT 10.0.18362
22 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
23 verbose node v10.14.2
24 verbose npm  v6.4.1
25 error code ELIFECYCLE
26 error errno 3221226356
27 error node-addon-api@3.0.1 test: `node test`
27 error Exit status 3221226356
28 error Failed at the node-addon-api@3.0.1 test script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 3221226356, true ]

**Comment by bzoz** [comment] 2020-07-14 09:49
Can reproduce with neither 12.18.2 and 14.5.0, with VS2019

Please provide:
 - entire `--verbose` log, put it inside backticks, like so:
<pre>
```
log goes here
```
</pre>
include the command that was used to run the test
- Node version, system version

Did you:
 - run `npm install`?
 - run `npm config set msvs_version [version you are using here]`?
 - install MS Build Tools or Visual Studio?

**Comment by mhdawson** [comment] 2020-07-14 22:32
@bzoz mentioned more info would be helpful.  Ideally enough so that we can add a test that would catch the failure in the future as current CI seems to be green: https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api-LTS%20versions/

**Comment by NickNaso** [comment] 2020-07-15 07:52
Hi @bzoz,
thanks for reporting the problem. Is your project public? Could your `binding.gyp` configuration ?

**Comment by NickNaso** [comment] 2020-07-15 20:08
This issue should be solved by the PR https://github.com/nodejs/node-addon-api/pull/766 or reverting the changes made by https://github.com/nodejs/node-addon-api/pull/757

**Comment by NickNaso** [comment] 2020-09-18 16:38
I'm closing because the v3.0.2 has been released and it should solve the problem.

**Closed by NickNaso** 2020-09-18 16:38 UTC
