### ISSUE TITLE
CI test failures on Windows

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/node-addon-api#627] opened 2019-12-09 21:54 UTC
We've been having some issues with Windows 10, especially when building against v8.x:

On the machines below, there is a consistent failure to remove a directory because one of the files is being used by a process, ultimately resulting in failure:

test-rackspace-win2012r2_vs2019-x64-6
test-rackspace-win2012r2_vs2019-x64-1
test-rackspace-win2012r2_vs2019-x64-3
test-rackspace-win2012r2_vs2019-x64-2

cc @nodejs/build ... ?

**Comment by gabrielschulhof** [comment] 2019-12-09 21:55
```
C:\workspace\node-test-node-addon-api-new\nodes\win-vs2019>rmdir C:\workspace\node-test-node-addon-api-new\nodes\win-vs2019 /s /q 
The process cannot access the file because it is being used by another process.
```

**Comment by gabrielschulhof** [comment] 2019-12-09 21:56
Maybe we need some Windows equivalent of
```
killall some_relevant_process
```
before we do the `rmdir`?

**Comment by richardlau** [comment] 2019-12-09 22:02
Not sure about the rmdir failures.
cc @joaocgreis

As for failures with Node.js 8 see: https://github.com/nodejs/build/issues/2084#issuecomment-563378847

PR to exclude Visual Studio 2019 from Node.js < 10 (since Node.js 8 ships with an older `npm`/`node-gyp`): https://github.com/nodejs/build/pull/2085

**Comment by gms1** [comment] 2020-01-06 09:51
> ```
> C:\workspace\node-test-node-addon-api-new\nodes\win-vs2019>rmdir C:\workspace\node-test-node-addon-api-new\nodes\win-vs2019 /s /q 
> The process cannot access the file because it is being used by another process.
> ```
I've had to deal with such errors many times; sometimes these are caused by virus scanners, sometimes by asynchronous behaviour (on network drives), but in this case it is probably caused by removing the current working directory

**Comment by mhdawson** [comment] 2020-01-06 22:40
@gabrielschulhof and I worked through this during Node+JS Interactive and we believe we updated the job to avoid the problem.  Believe it was a result of not having removed a command that did not seem to do anything on WIndows. Now it is cased out and looks like we've had good results since.  Closing.

**Closed by mhdawson** 2020-01-06 22:40 UTC
