### ISSUE TITLE
Not building on node 8.2.1

### ISSUE THREAD

**Issue by mcollina** [nodejs/node-addon-api#99] opened 2017-08-02 07:36 UTC
```
In file included from /Users/matteo/Repositories/native-hdr-histogram/node_modules/node-addon-api/napi.h:1447:
/Users/matteo/Repositories/native-hdr-histogram/node_modules/node-addon-api/napi-inl.h:1461:20: error: no matching function for call to 'napi_create_type_error'
          status = napi_create_type_error(env, nullptr, message, &error);
                   ^~~~~~~~~~~~~~~~~~~~~~
```

I think this is due to a semver-major change happening in core for the new error codes. In case such events happen again, this module should be released to NPM after the change lands in a release.

**Comment by jasongin** [comment] 2017-08-02 18:00
The `node-addon-api` is in sync with the latest in node master. The problem is that breaking change didn't make it into an 8.x release yet. This will resolve itself in time.

**Comment by jasongin** [comment] 2017-08-02 22:30
What I meant was, the change was [merged into the node 8.x branch last week](https://github.com/nodejs/node/pull/14453), so it should be in the v8.3.0 release.

**Comment by mhdawson** [comment] 2017-08-17 22:34
Thats probably my fault as I'm generally using master versus the releases but most module maintainers are going to be using the official releases.  An earlier version would probably work, but its not necessarily easy for maintainers to know.  We should only have 1-2 more cases where this happens as we should be locking things down within a few weeks.

**Comment by mcollina** [comment] 2017-08-18 07:46
We should have a strategy to support node versions until we freeze the API.

**Comment by mhdawson** [comment] 2017-10-23 15:54
I think we can close this, please re-open if that is not the case.

**Closed by mhdawson** 2017-10-23 15:54 UTC
