### ISSUE TITLE
ObjectWrap and destructor

### ISSUE THREAD

**Issue by kaanmehmetaksoy** [nodejs/node-addon-api#450] opened 2019-02-18 08:34 UTC
I'm using global.gc() to call the destructor method of the class derived from ObjectWrap. Isn't it possible to do this automatically? Actually I don't want to use global.gc().

**Comment by legendecas** [comment] 2019-02-20 03:42
GC would be triggered once certain criteria were matched. `global.gc` just forced a GC to be ran.

If certain operations must be performed in time, some methods like `close` or `shutdown` could be implemented and be invoked manually instead of waiting for object's to be gc-ed.

**Comment by gabrielschulhof** [comment] 2019-02-20 03:52
@kaanmehmetaksoy IMO your code should not have to rely on the destructor getting called. You should move whatever important things the destructor does into a method as @legendecas suggested and call that method instead of `global.gc()`, especially since calling `global.gc()` is no guarantee that the wrapping JavaScript object will be gc-ed, thereby causing the destructor to be called.

If you factor the code out into such a method and call it manually, you can call it reliably and the destructor will do nothing but deallocate the instance of the `ObjectWrap` subclass whenever the JavaScript object wrapper goes out of scope.

**Comment by kaanmehmetaksoy** [comment] 2019-02-23 09:28
@legendecas and @gabrielschulhof Thanks for solution. I have designed all the classes in my library like as your suggested. now all of them have shutdown function triggering the destructor. and I will call it manually when needed. i want to avoid memory leak. my raspberrypi should be working long time without stopping.

**Comment by mhdawson** [comment] 2019-03-04 21:33
@kaanmehmetaksoy I see you closed and re-opened.  It looks like your questions were answered discussion that needs to take place before the issue is closed?

**Comment by raptor9g** [comment] 2019-07-18 17:55
Instead of the relying on the dtor.  Exposing the `napi_finalize` argument to classes warped by ObjectWrap would be more in line with the C lib intent.  I think part of the problem is that this part of the underling C library has been obscured.

I see that [`ObjectWrap` ctor calls `napi_wrap`](https://github.com/nodejs/node-addon-api/blob/ac6000d0fd9c49b87748e6a3a1e2b83479b4b0a2/napi-inl.h#L2882) and passes static `ObjectWrap::FinalizeCallback` as the `napi_finalize` to `napi_wrap`.

I understand that `ObjectWrap::FinalizeCallback` needs to run, could it not be wrapped with a user defined `napi_finalize` argument?

**Comment by raptor9g** [comment] 2019-07-19 01:35
> Instead of the relying on the dtor. Exposing the `napi_finalize` argument to classes warped by `ObjectWrap` would be more inline with the C lib intent. I think part of the problem is that this part of the underling C library has been obscured.
> 
> I see that [`ObjectWrap` ctor calls `napi_wrap`](https://github.com/nodejs/node-addon-api/blob/ac6000d0fd9c49b87748e6a3a1e2b83479b4b0a2/napi-inl.h#L2882) and passes static `ObjectWrap::FinalizeCallback` as the `napi_finalize` to `napi_wrap`.
> 
> I understand that `ObjectWrap::FinalizeCallback` needs to run, could it not be wrapped with a user defined `napi_finalize` argument?

This wraps a user defined `napi_finalize` and exposes it via a protected member that can be set in the derived class most likely the ctor.
raptor9g/node-addon-api@7f534521b281e724c7244a8b51c3d4c40b3a057f

I contend that the central theme of [Object Wrap](https://nodejs.org/api/n-api.html#n_api_object_wrap) is encapsulation.  Specifically tying the lifetime of a JS object to a C++ class instance.  The implementation of [ObjectWrap::FinalizeCallback](https://github.com/nodejs/node-addon-api/blob/d9d991bbc9ef7a3364f83bdf43bce6e956075188/napi-inl.h#L3403) demonstrates this assertion as the freeing of the native object is not optional.

Allowing for an optional user defined `napi_finalize` opens the door for clean up that requires calls to other N-API methods.  And, as apposed to the native instance dtor, keeps these actions in the N-API ecosystem.

The above implementation respects the opinionated `ObjectWrap::FinalizeCallback` implementation as it does not override the non-optional freeing of the C++ instance.  Note that in the N-API version this is optional.

An alternative non-breaking approach might be to allow OVERRIDING of the `ObjectWrap::FinalizeCallback` if a user defined `napi_finalize` is provided.  In which case the responsibility of the native object memory management would fall to the user defined `napi_finalize`.  This might be preferable for 2 reasons:

1. It allows for the N-API's optionality in freeing the native instance.
2. Eliminates the possibility of a conflict between `ObjectWrap::FinalizeCallback`'s freeing operation and a freeing operation in the user defined `napi_finalize`.

**Comment by mhdawson** [comment] 2019-07-22 22:05
I'm going to close, please let me know if that is not the right thing to do.

**Closed by mhdawson** 2019-07-22 22:05 UTC
