### ISSUE TITLE
`Error: Invalid argument` when calling Napi::Function

### ISSUE THREAD

**Issue by devsnek** [nodejs/node-addon-api#172] opened 2017-10-28 22:55 UTC
I'm working on a native EventEmitter, and i'm getting invalid argument when calling the handlers in a loop, but nowhere else. see the comments in the screenshots for more info.

![](https://gc.gy/裂❟⟸.png)
![](https://gc.gy/⟴ɀ凌.png)

**Comment by bnoordhuis** [comment] 2017-10-29 09:19
Can you post a more complete code example?  It's impossible to tell what the issue is right now.

**Comment by devsnek** [comment] 2017-10-29 15:18
The problem code is here
https://github.com/devsnek/eventemitter-native/blob/66902e3806359f2cec219aae62fcaa984aaeaf17/src/EventEmitter.cc#L84-L91

**Comment by bnoordhuis** [comment] 2017-10-30 15:25
Don't know if it's the cause but by the looks of it, the `once` and `every` collections can get mutated while they're being iterated over (loop calls into JS, JS can call mutator methods.)

**Comment by devsnek** [comment] 2017-10-30 15:41
@bnoordhuis so is this an n-api issue or should i close this

**Comment by bnoordhuis** [comment] 2017-10-30 16:37
I'd close it unless you've conclusively established it's a napi issue.

**Comment by devsnek** [comment] 2017-10-30 17:41
@bnoordhuis i guess this is out of scope of the issue, but do you have any knowledge of how to fix this? i'm not very experienced with any of the addon apis

**Comment by bnoordhuis** [comment] 2017-10-30 17:54
Iterate over a copy of the list.  The built-in EventEmitter does the same thing.

**Comment by devsnek** [comment] 2017-10-30 21:00
@bnoordhuis i tried making a copy but it has the same error, i'm hopeful i just did this completely wrong
```cpp
    std::vector<Napi::Function> copy(this->every[name].begin(), this->every[name].end());
    for (Napi::Function const& handler: copy)
      handler.Call(callArgs); // same error as before
```

**Comment by devsnek** [comment] 2017-10-31 03:19
after talking with my friend who actually knows c++, i'm gonna repoen this, seems like undefined behavior

**Comment by bnoordhuis** [comment] 2017-10-31 10:52
UB how and where?

**Comment by guymguym** [comment] 2017-11-02 18:24
@devsnek I might be off here, but seems to me like you keep the functions in your class members after the javascript scope that contained them (the scope of the On() function) already returned, and the local reference you had is invalidated. 

In order to keep values after the local scope returns you will need to create a reference, which for convinience has an Napi::FunctionReference class you can use:
https://nodejs.github.io/node-addon-api/class_napi_1_1_function_reference.html

Notice that even the Napi::String values you used for keys are invalidated so you better just use std::string for your map keys.

Try something like this:

```
class EventEmitter : public Napi::ObjectWrap<EventEmitter> {

    Napi::Value On(const Napi::CallbackInfo& info) {
        Napi::String name = info[0].As<Napi::String>();
        Napi::Function handler = info[1].As<Napi::Function>();
        handlers[name].push_back(Napi::FunctionReference::New(handler, 1));
    }

    Napi::Value Emit(const Napi::CallbackInfo& info) {
        Napi::String name = info[0].As<Napi::String>();
        for (Napi::FunctionReference const& handler: handlers[name])
            handler.Call(callArgs);
    }

    std::map<std::string, std::vector<Napi::FunctionReference>> handlers;
};
```

BTW You should still make a copy of the vector before calling the handlers in case the handlers will decide to call `On()` or `RemoveListener()` which will change the vector during the iteration, but I didn't write that part to make the point.

Hope that helps.

**Comment by guymguym** [comment] 2017-11-03 08:42
@bnoordhuis I think this issue can be closed. Hope that helps.

**Closed** 2017-11-03 12:44 UTC

**Comment by vinnitu** [comment] 2019-06-19 09:53
how to pass arguments to Call() properly?
