### ISSUE TITLE
node-gyp Python 3 support

### ISSUE THREAD

**Issue by bsrdjan** [nodejs/node-addon-api#445] opened 2019-02-11 14:27 UTC
Considering Python 2 will not be maintained past 2020 and [node-gyp Python 3 support](https://github.com/nodejs/node-gyp/issues/1337) looks unclear, any thoughts here how building N-API modules could look like in a year from now? Any alternatives to start exploring now?

**Comment by NickNaso** [comment] 2019-02-11 14:56
@bsrdjan You are right, we start thinking about the problem you reported and in general it's a problem that interests all the Node.js ecosystem.

**Comment by mhdawson** [comment] 2019-02-11 15:44
@bsrdjan thanks for adding this to the radar.  It's not specific to N-API as it will affect all modules.  We should probably consider how this aspect should be included in: https://github.com/nodejs/TSC/issues/642

**Comment by mhdawson** [comment] 2019-02-11 15:49
Related: https://github.com/nodejs/node-gyp/issues/1337

**Comment by Yzrsah** [comment] 2019-02-13 11:28
https://chromium.googlesource.com/experimental/chromium/src/+/refs/wip/bajones/webvr/tools/gn/docs/cookbook.md

**Comment by Yzrsah** [comment] 2019-02-13 11:29
[GYP->GN Conversion Cookbook](https://chromium.googlesource.com/experimental/chromium/src/+/refs/wip/bajones/webvr/tools/gn/docs/cookbook.md)

**Comment by Yzrsah** [comment] 2019-02-13 11:36
[GYP->GN Conversion Cookbook](https://chromium.googlesource.com/experimental/chromium/src/+/refs/wip/bajones/webvr/tools/gn/docs/cookbook.md)

[The build system](https://fuchsia.googlesource.com/fuchsia/+/master/docs/development/build/overview.md)

**Comment by darknoon** [comment] 2019-04-28 20:58
I have been using CMake via CMake.js and am pretty happy with it so far.

Seems to "just work" a lot more. Very nice if you're linking modules that it knows how to find across platforms (been messing w/ PyTorch & generic Python3 modules for N-API).

**Comment by pmahend1** [comment] 2019-08-19 16:01
yes we need python 3 support. @darknoon  could you please document the steps using Cmake.js instead of plain old npm build with python2?

**Comment by bsrdjan** [comment] 2019-08-25 15:06
Porting my node-gyp [binding.gyp](https://github.com/SAP/node-rfc/blob/cmake/binding.gyp) to cmake-js [CMakeLists.txt](https://github.com/SAP/node-rfc/blob/cmake/CMakeLists.txt) was relatively simple. It works on Linux and Darwin and on Windows still some issues but nothing critical.

As @darknoon mentioned, the build itself "just works" and here what I feel missing from node-gyp:

1. The node-gyp installs node headers, cmake-js not. My node version managers install headers on Linux and Darwin but not on Windows, a minor issue.

2. The node-pre-gyp can download platform/node dependent binaries from github, as configured in [binary](https://github.com/SAP/node-rfc/blob/cmake/package.json#L30) package.json section. Found no cmake alternative, [pre-cmake](https://github.com/simon-p-r/pre-cmake-js) is inactive. The workaround would be adding all platform/node dependent binaries to lib/bindings folder, so that all of them are installed, on every platform. Any suggestions here?

3. [node-pre-gyp](https://github.com/SAP/node-rfc/blob/napi/src/ts/wrapper/sapnwrfc-client.ts#L4) addon loader must be replaced, [bindings](https://github.com/SAP/node-rfc/blob/cmake/src/ts/wrapper/sapnwrfc-client.ts#L7) work fine.

**Comment by bsrdjan** [comment] 2019-08-29 09:21
Packing binaries for all platforms and node versions into single npm package, would increase the package size to several MB, which is considered a npm anti-pattern. A mechanism like node-pre-gyp is required, to fetch a single platform/node-abi binary from github during npm install. Fixing rather minor pre-cmake-js gaps would work for me but and I am interested in how other node addon developers using cmake solve this problem?

**Comment by mhdawson** [comment] 2019-08-29 20:52
I'm pretty sure that @jschlight metioned he'd done some related work for one of the packages which allows you to build with cmake, just not sure if it was pre-cmake-js.  @jschlight can you let us know which one it was?

**Comment by sam-github** [comment] 2019-09-04 16:30
For the record:

> node-gyp Python 3 support looks unclear

python3 should be supported: https://github.com/nodejs/node-gyp/issues/1337#issuecomment-508988254

If there are problems, they will have to be fixed.

Starting to support cmake as an alternative to gyp sounds fine, but I don't think the node.js pro/npm/node-gyp projects have any choice other than to support gyp for building node addons for a fair while, certainly pass the EOL of python2.

Which in no way means that exploring alternatives should not move ahead.

**Comment by bsrdjan** [comment] 2019-09-20 10:03
My status:

1) `cmake` still the same: https://github.com/nodejs/node-addon-api/issues/445#issuecomment-524637344. Here my [cmake branch](https://github.com/SAP/node-rfc/tree/cmake), ported from [napi](https://github.com/SAP/node-rfc/tree/napi).

2) With the `node-gyp` latest release, I am still getting "Python 3 not supported" error. Reading https://github.com/nodejs/node-gyp/issues/1337#issuecomment-508988254, I could not figure out which node-gyp should work with Python 3 and how to install it? Did anyone try building NAPI add-on with node-gyp and Python 3 and how to start?

I have no preferences for either of these solutions, just need a working one. Have a feeling the `cmake` way might be simpler/shorter, for the time being, especially if https://github.com/mapbox/node-pre-gyp/issues/205 works.

**Comment by sam-github** [comment] 2019-09-20 15:31
Did you set `EXPERIMENTAL_NODE_GYP_PYTHON3="yes"` in the environment?

**Comment by bsrdjan** [comment] 2019-09-24 09:12
Yes and the configure ends with: ModuleNotFoundError: No module named 'compiler'

```shell
$ node-gyp --version
v5.0.3
$ node-pre-gyp --version
v0.13.0
$ python -V
Python 3.7.4
$ export EXPERIMENTAL_NODE_GYP_PYTHON3=yes
$ node-pre-gyp configure
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@10.16.3 | darwin | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.16.3 | darwin | x64
gyp info find Python using Python version 3.7.4 found at "/Users/d037732/.pyenv/versions/py374/bin/python"
gyp info spawn /Users/d037732/.pyenv/versions/py374/bin/python
gyp info spawn args [ '/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/d037732/src/NG-APPS/node-rfc/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/d037732/Library/Caches/node-gyp/10.16.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/d037732/Library/Caches/node-gyp/10.16.3',
gyp info spawn args   '-Dnode_gyp_dir=/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/d037732/Library/Caches/node-gyp/10.16.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/d037732/src/NG-APPS/node-rfc',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp/gyp/gyp_main.py", line 13, in <module>
    import gyp
  File "/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 10, in <module>
    import gyp.input
  File "/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 7, in <module>
    from compiler.ast import Const
ModuleNotFoundError: No module named 'compiler'
```

According to Python documentation, the compiler module is removed in Python 3: https://docs.python.org/2/library/compiler.html

**Comment by sam-github** [comment] 2019-09-24 17:24
@bsrdjan v5.0.3 doesn't support py3, try master. I've asked node-gyp to publish, see https://github.com/nodejs/node-gyp/issues/1791#issuecomment-534243680 and preceeding conversation.

**Comment by bsrdjan** [comment] 2019-09-25 09:41
Thanks @sam-github. With EXPERIMENTAL_NODE_GYP_PYTHON3="yes" it works on Linux and fails on macOS and Windows:

**macOS** (Xcode and CLT are installed)

```shell
$ node-pre-gyp configure

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@10.16.3 | darwin | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.16.3 | darwin | x64
gyp info find Python using Python version 3.7.4 found at "/Users/d037732/.pyenv/versions/py374/bin/python"
gyp info spawn /Users/d037732/.pyenv/versions/py374/bin/python
gyp info spawn args [ '/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/d037732/src/NG-APPS/node-rfc/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/d037732/Library/Caches/node-gyp/10.16.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/d037732/Library/Caches/node-gyp/10.16.3',
gyp info spawn args   '-Dnode_gyp_dir=/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/d037732/Library/Caches/node-gyp/10.16.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/d037732/src/NG-APPS/node-rfc',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
gyp: No Xcode or CLT version detected!
```

**Windows**
```shell
$ node-pre-gyp configure
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@10.15.3 | win32 | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.15.3 | win32 | x64
gyp info find Python using Python version 3.7.4 found at "C:\Tools\Python374\python.exe"
gyp info find VS using VS2017 (15.7.27703.2026) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Tools\Python374\python.exe
gyp info spawn args [ 'C:\\src\\node-rfc\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\src\\node-rfc\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\src\\node-rfc\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\d037732\\AppData\\Local\\node-gyp\\Cache\\10.15.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\d037732\\AppData\\Local\\node-gyp\\Cache\\10.15.3',
gyp info spawn args   '-Dnode_gyp_dir=C:\\src\\node-rfc\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\d037732\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\10.15.3\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\src\\node-rfc',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\src\\node-rfc\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "C:\src\node-rfc\node_modules\node-gyp\gyp\gyp_main.py", line 44, in <module>
    sys.exit(gyp.script_main())
  File "C:\src\node-rfc\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "C:\src\node-rfc\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 547, in main
    return gyp_main(args)
  File "C:\src\node-rfc\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\src\node-rfc\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2040, in GenerateOutput
    version=msvs_version)
  File "C:\src\node-rfc\node_modules\node-gyp\gyp\pylib\gyp\MSVSNew.py", line 208, in __init__
    self.Write()
  File "C:\src\node-rfc\node_modules\node-gyp\gyp\pylib\gyp\MSVSNew.py", line 233, in Write
    all_entries = sorted(all_entries)
TypeError: '<' not supported between instances of 'MSVSFolder' and 'MSVSProject'
gyp ERR! configure error
```

**Comment by sam-github** [comment] 2019-09-25 18:35
@bsrdjan I'm a bit confused. You are using node-pre-gyp, not node-gyp, and node-pre-gyp is using `gyp info using node-gyp@5.0.3` according to your output, not node-gyp master. I think you might need to wait until node-gyp is published, and the downstreams use it, unless you want to manually patch node-gyp@master into  your deps, just to give feedback on what is broken  with py3 (and there are surely things broken).

**Comment by cclauss** [comment] 2019-09-25 19:02
The Python stack trace is saying that __all_entries__ contains at least one __MSVSFolder__ and at least one __MSVSProject__ and that is like tryingt to do __sort(apples, oranges)__.  This is probably caused by `__cmp__()` being removed in Python 3...  I will dig in.

**Comment by cclauss** [comment] 2019-09-25 22:12
The macOS issue should be fixed in nodejs/node-gyp#1890

**Comment by bsrdjan** [comment] 2019-09-26 06:37
@sam-github it shows 5.0.3 but it is the master branch, here my [package.json.zip](https://github.com/nodejs/node-addon-api/files/3656254/package.json.zip). Testing with pre-gyp convenient for me because no changes in my binding.gyp needed.

I re-tested with macOS and the error message is now different:

```shell
$ export EXPERIMENTAL_NODE_GYP_PYTHON3=yes                                                                                                                                    
$ node-pre-gyp configure
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@10.16.3 | darwin | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.16.3 | darwin | x64
gyp info find Python using Python version 3.7.4 found at "/Users/d037732/.pyenv/versions/py374/bin/python"
gyp info spawn /Users/d037732/.pyenv/versions/py374/bin/python
gyp info spawn args [ '/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/d037732/src/NG-APPS/node-rfc/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/d037732/Library/Caches/node-gyp/10.16.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/d037732/Library/Caches/node-gyp/10.16.3',
gyp info spawn args   '-Dnode_gyp_dir=/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/d037732/Library/Caches/node-gyp/10.16.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/d037732/src/NG-APPS/node-rfc',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp/gyp/gyp_main.py", line 44, in <module>
    sys.exit(gyp.script_main())
  File "/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2215, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 802, in Write
    self.WriteCopies(spec['copies'], extra_outputs, part_of_all)
  File "/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1145, in WriteCopies
    env = self.GetSortedXcodeEnv()
  File "/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1885, in GetSortedXcodeEnv
    additional_settings)
  File "/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1616, in GetSortedXcodeEnv
    additional_settings)
  File "/Users/d037732/src/NG-APPS/node-rfc/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1527, in _GetXcodeEnv
    if XcodeVersion() >= '0500' and not env.get('SDKROOT'):
TypeError: '>=' not supported between instances of 'tuple' and 'str'
gyp ERR! configure error 
```

**Comment by sam-github** [comment] 2019-09-26 22:13
@bsrdjan That makes sense, I forgot that master's package has 5.0.3 in it :-)

@cclauss might have ideas on the specific error.

You package isn't on github or otherwise publically available/reproducible, is it? If the build was reproducible, it's probably be faster to fix than round-tripping through here.

**Comment by bsrdjan** [comment] 2019-09-27 12:27
Yes, it would simplify the testing and conversation.

The github project is sap/node-rfc and the working branch, built with Python2, is [napi](https://github.com/SAP/node-rfc/tree/napi). The releases of this branch are linked to npm [node-rfc](https://www.npmjs.com/package/node-rfc) package pre-releases (npm install node-rfc@next).

Above mentioned issues should be reproducible with [gyp3](https://github.com/SAP/node-rfc/tree/gyp3) branch, used for Python3 builds.

The [cmake](https://github.com/SAP/node-rfc/tree/cmake) branch  has no issues with Python 3 but others: https://github.com/nodejs/node-addon-api/issues/445#issuecomment-524637344.

**Comment by jschlight** [comment] 2019-09-27 18:50
[CMake.js](https://github.com/cmake-js/cmake-js#cmakejs-mit) is a viable alternative to [node-gyp](https://github.com/nodejs/node-gyp#node-gyp---nodejs-native-addon-build-tool) for building Node N-API native addons. The N-API Team has created an [example project](https://github.com/nodejs/node-addon-examples/tree/master/build_with_cmake) that shows how this can be accomplished. 

In addition, [prebuild](https://github.com/prebuild/prebuild#prebuild) now supports CMake.js as a build backend for N-API native addons. The specifics can be found in the [documentation](https://github.com/prebuild/prebuild#n-api-considerations). prebuild is of interest to Node native addon maintainers using GitHub as it facilitates the building and uploading of native addon binaries as GitHub releases. This permits users of the native addon to download the binary from GitHub instead of needing to have the necessary build tools installed on their development and deployment machines.

**Comment by bsrdjan** [comment] 2019-10-01 10:02
Thanks @jschlight, for the the [prebuild](https://github.com/prebuild/prebuild#prebuild) hint. 

My [project](https://github.com/SAP/node-rfc/tree/napi) works with CMake now, on Linux, Windows and macOS and this issue can be closed AFAIAC.

**Comment by mhdawson** [comment] 2019-10-01 17:53
@bsrdjan thanks for the update, closing

**Closed by mhdawson** 2019-10-01 17:53 UTC

**Comment by jschlight** [comment] 2019-10-07 01:58
@bsrdjan You might consider adding an N-API Badge to your README file. The details are [here](https://github.com/nodejs/abi-stable-node#nodejs-api-n-api).

**Comment by bsrdjan** [comment] 2019-10-07 07:22
thanks, done.
