### ISSUE TITLE
npm test is failed on earlier Node.js versions

### ISSUE THREAD

**Issue by nadongguri** [nodejs/node-addon-api#409] opened 2018-12-17 01:16 UTC
Hi, node-addon-api,

I've checked 'npm test' with earlier Node.js versions (v8.9.4) on linux env and
some tests such as bigint, callbackscope are required to higher version of Node.js.

Checking napi version is already in test/index.js but the value process.env.npm_config_NAPI_VERSION
is undefined on my setup, so.. users should set that value? (I have searched npm_config_NAPI_VERSION in the node and node-addon-api source but I couldn't find the define).
Or is it fine to modify that code in test/index.js by using a node version to pass tests?

**Comment by NickNaso** [comment] 2018-12-17 13:54
Hi @nadongguri,
could you specify the Node.js versions that present the problem?

**Comment by NickNaso** [comment] 2018-12-17 14:35
Are you using **nvm**?

**Comment by nadongguri** [comment] 2018-12-17 14:50
Hi @NickNaso,
I used to download Nodejs in https://nodejs.org/dist but now I can use nvm. :)
I've installed nvm, downloaded few versions of nodejs and tested. Still I get the same result.

**Comment by NickNaso** [comment] 2018-12-17 14:59
I want better understand the problem:
Could you try this?
`nvm list`
The output should be something like this:
<img width="341" alt="screenshot 2018-12-17 at 15 52 23" src="https://user-images.githubusercontent.com/387506/50094883-7cecb580-0214-11e9-96dc-d89420be2c1b.png">
Then if you have **system** you can switch to system version:
`nvm use system`
Try to execute the test suite after this switch and if you don't have the problem is something correlated with **nvm** otherwise we need to investigate more deeply.

**Comment by nadongguri** [comment] 2018-12-17 15:17
Hi @NickNaso,

```
ryan@ryan-Inspiron-7566:~/Desktop/node/node-addon-api$ nvm list
->      v8.14.0
        v11.4.0
         system
default -> node (-> v11.4.0)
node -> stable (-> v11.4.0) (default)
stable -> 11.4 (-> v11.4.0) (default)
niojs -> N/A (default)
vlts/* -> lts/dubnium (-> N/A)
mlts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.15.1 (-> N/A)
lts/carbon -> v8.14.0
lts/dubnium -> v10.14.2 (-> N/A)

ryan@ryan-Inspiron-7566:~/Desktop/node/node-addon-api$ nvm use system
Now using system version of node: v8.12.0 (npm v6.4.1)
```
As you see system's verison is v8.12.0. With the latest clean node-addon-api code in master branch,
"npm test" is failed at the bigint test.

```
> node-addon-api@1.6.2 test /home/ryan/Desktop/node/node-addon-api
> node test

Starting test suite

Running test 'arraybuffer'
Running test 'asynccontext'
Running test 'asyncworker'
Running test 'basic_types/array'
Running test 'basic_types/boolean'
Running test 'basic_types/number'
Running test 'basic_types/value'
Running test 'bigint'
/home/ryan/Desktop/node/node-addon-api/test/bigint.js:19
    0n,
    ^

SyntaxError: Invalid or unexpected token

```

I'm wondering when process.env.npm_config_NAPI_VERSION is set... or I can add code to check nodejs and napi version then skip those test cases with unproper nodejs.

**Comment by mhdawson** [comment] 2018-12-18 22:47
Out CI sets the NAPI_VERSION as follows

```bash
echo 'console.log(process.versions.napi)' >get_napi_version.js
NAPI_VERSION_REPORTED=`node get_napi_version.js`
npm test --NAPI_VERSION=$NAPI_VERSION_REPORTED
```

We should probably document this somewhere.  I think I had tried to make it automatically default to the right value but was not successful.

**Comment by mhdawson** [comment] 2020-12-07 19:41
I recently added some additional detail in this section: https://github.com/nodejs/node-addon-api#tests. Closing. Please let us know if that was not the right thing to do.

**Closed by mhdawson** 2020-12-07 19:41 UTC
