### ISSUE TITLE
/src/node_api.h lack function declaration of napi threadsafe_function

### ISSUE THREAD

**Issue by er230059** [nodejs/node-addon-api#641] opened 2019-12-26 01:46 UTC
`node_api.h` not has napi threadsafe_function
(https://nodejs.org/dist/latest-v12.x/docs/api/n-api.html#n_api_napi_create_threadsafe_function)
```
napi_create_threadsafe_function
napi_get_threadsafe_function_context
napi_call_threadsafe_function
napi_acquire_threadsafe_function
napi_release_threadsafe_function
napi_ref_threadsafe_function
napi_unref_threadsafe_function
```
It cause my IDE always  show error when I use those function.

**Comment by legendecas** [comment] 2019-12-26 02:20
Possible duplicated with https://github.com/nodejs/node-addon-api/issues/463.

**Comment by gabrielschulhof** [comment] 2020-01-01 05:18
Actually, a duplicate of #509.

**Closed by gabrielschulhof** 2020-01-01 05:18 UTC
